### ISSUE TITLE
Please check the compute method for CPI.

### ISSUE THREAD

**Issue by LingAndZero** [ZJU-SPAIL/pipa#23]
In the file perf_stat.py, the CPI is calculated by averaging the CPIs of the participating cores.
I am not sure that is right.
My compute method is totalCycles / totalInstructions.
The results are quite different between the two approaches.

**Comment by bernard035** [comment]
Regarding your question, I will rephrase it.

Average CPI (Current PIPA used):
- Definition: The average CPI is the mean CPI of each core.
- Calculation: For each core, calculate its own CPI, and then take the arithmetic mean of all the cores' CPIs.
- Formula:${{Average CPI} = \frac{CPI_1 + CPI_2 + ... + CPI_n}{n}}$

Weighted CPI (You proposed):
- Definition: The weighted CPI takes into account the activity level or workload of each core to better reflect the overall system performance.
- Calculation: Sum up all the cycles and instructions across all cores, and then divide the total cycles by the total instructions.
- Formula: If the total cycles across all cores are $C_{total}$ , and the total instructions are $I_{total}$
$Weighted CPI = \frac{C_{total}}{I_{total}}$

---

- Average CPI provides the average performance metric for each core, which is useful for understanding the average performance of individual cores.
- Weighted CPI offers a more comprehensive view of the system's performance, especially when the workload across cores is uneven.

Thank you for your suggestion. PIPA will use weighted CPI.
